if (signaturePad.isEmpty()) {
    sap.m.MessageToast.show("Please sign");
} else {
    imgSign.setSrc(signaturePad.toDataURL());
    sap.m.MessageToast.show("Signature saved into base64");

    resetSignatureButton.setEnabled(false);
    
    saveSignatureButton.setType('Accept');
    saveSignatureButton.setEnabled(false);

    oHTMLObjectSignaturePad.setVisible(false);
    imgSign.setVisible(true);

    tabSignView.setIconColor('Positive');

    checkIfReadyToSubmit()
}
